### PR TITLE
Fix detour on popups

### LINKED ISSUE #21: Detour from `:ZenMode` or `:Lazy` results in error
Repro: 

1. use https://github.com/folke/zen-mode.nvim
2. enter zen-mode by issuing `:ZenMode`.
3. issue `:Detour`

Error message:

```
E5108: Error executing lua: ...s/.local/share/nvim/lazy/detour.nvim/lua/detour/init.lua:154: attempt to perform arithmetic on a nil value
stack traceback:
	...s/.local/share/nvim/lazy/detour.nvim/lua/detour/init.lua:154: in function 'nested_popup'
	...s/.local/share/nvim/lazy/detour.nvim/lua/detour/init.lua:188: in function 'popup'
	...s/.local/share/nvim/lazy/detour.nvim/lua/detour/init.lua:255: in function 'Detour'
	/Users/neilvyas/.config/nvim/init.lua:53: in function </Users/neilvyas/.config/nvim/init.lua:52>
```

Other popups, like `:Lazy`, still work from within zen-mode. Detour is very useful (or, will be, once this bug is addressed) in conjunction with zen-mode since zen-mode exits automatically when attempting to navigate away from its window or on many other triggers; popups do not exit it. So, I wanted to use Detour to have access to neogit from within zen-mode.

I haven't done any debugging yet, other than a cursory examination of the reported error site. I'm just logging this issue now so that I don't forget to!

### PR DESCRIPTION
**Pull request by neilvyas**
Fixes #21 

NOTE: the docker setup didn't work for me, so I had to spend a little time hacking around to get it to work.

Also, lua... seems really annoying to work with? it keeps editing my .gitignore to add /lua, which means that the actual plugin files are ignored. Plus, the last step of the dockerfile, RUN luarocks install, doesn't seem to actually install busted, hence why I had to do it in the script; I think this is because of how volume mounting works in docker. Dunno, been years since I've used it.

This should probably not be left in as a commit, and should be corrected separately, but I'm not going to get to that out. If an dwhen we decide to merge this, we can leave this commit out.

Anyway, I've corrected the issue and added test coverage. The test coverage is not to my satisfaction, but I'm not going to try to fix it at the moment, given that I'd have to learn how busted and testing generally works in lua; as such, I've left a helpful note.

### CODE REVIEW

**Comment by carbon-steel** [comment]
Sorry, I won't be able to review this code tonight. Am feeling unwell :(

**Comment by neilvyas** [comment]
no rush, feel better soon!

File: run-in-docker.sh [hunk 1]
```diff
@@ -1,6 +1,9 @@
 #!/bin/sh
-# luarocks init
-# luarocks config --scope project lua_version 5.1
+#
+luarocks init
+luarocks config --scope project lua_version 5.1
+luarocks install busted 2.1.2-3
```
Comment (carbon-steel) [inline run-in-docker.sh:5]: I didn't realize that there would be issues with running the tests (sorry about that). This is definitely something that needs to be addressed, but I'd prefer to address it in a separate PR to keep this PR more focused. For now, could we remove the changes to this file?

File: spec/detour_spec.lua [hunk 2]
```diff
@@ -57,6 +58,48 @@ describe("detour", function ()
...
+    end)
+    -- TODO: technically, either 
+    --   1) all test cases involving nested popups need to be tested with both
+    --      nested Detour popups and nested windows generally; or
+    --   2) we must ensure that detour.Detour() behaves identically when nesting over either of the
+    --      objects just mentioned.
+    -- Approach (2) is clearly superior, but it's not clear (to neilvyas) how to accomplish that;
+    -- as such, perhaps the better approach is to abstract all nesting-related coverage into a
+    -- function which accepts a "popup constructor" and produces test cases, then invoke this
+    -- function twice, once with a constructor for detour.Detour() and another for general popups.
```
Comment (carbon-steel) [inline spec/detour_spec.lua:101]: I think this text goes beyond just a simple TODO but should instead be a conversation on a github issue (where the conversation can be tracked). Could you move this message to a github issue?

**Review by carbon-steel — CHANGES_REQUESTED** [review]
Nicely done! I think this PR is ready to be merged to dev after addressing a couple nits :). Thanks so much for your contribution :)

File: run-in-docker.sh (hunk 1 above)
Comment (neilvyas) [reply run-in-docker.sh:5]: That was my intent, yes; I just left it in here so that you'd see it.

I can try setting up the tests in a slightly different way in a different PR which might be more portable.

File: spec/detour_spec.lua (hunk 2 above)
Comment (neilvyas) [reply spec/detour_spec.lua:101]: aye aye!

Comment (neilvyas) [reply spec/detour_spec.lua]: moved the discussion to #25

**Comment by neilvyas** [comment]
ready for review!

**Comment by carbon-steel** [comment]
Really good job! Not only did you fix the bug, but you also simplified the code at the same time :)
